### PR TITLE
Add todo list component

### PR DESCRIPTION
**Pull request by AidaBur**

### CODE REVIEW

**Comment by AidaBur** [comment]
I might have made a mistake by creating the branch first before committing. When I tried to make a pull request, I noticed that there was no main branch, so I had to create one. Now, the main branch looks the way the lesson_1_1 branch should have looked. I hope this isn’t too critical for this assignment

**Review by AnnaSolovykh — APPROVED** [review]

**Comment by AnnaSolovykh** [comment]
The assignment looks good to me but seems like this branch is the default one, which is not correct - the main branch should be default. image

**Comment by AnnaSolovykh** [comment]
Do you need help in changing the default branch?

**Comment by AidaBur** [comment]
> Do you need help in changing the default branch?

Anna, thank you so much, I think I found how to change it.
Screen Shot 2024-11-11 at 8 55 08 AM

**Comment by AnnaSolovykh** [comment]
Well done!

**Pull request merged**
